# -*- coding: utf-8 -*-
"""RL-Index.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nn-C4t_7Rd4FYw0rhuvjq-ynrccXSOia
"""

!pip install -q sentence-transformers
!pip install -q faiss-cpu
!pip install -q openai
!pip install -q pandas
!pip install -q numpy

import os
import json
import faiss
import numpy as np

from sentence_transformers import SentenceTransformer
from openai import OpenAI

OPENROUTER_API_KEY = "YOUR_API_KEY"

client = OpenAI(
    api_key=OPENROUTER_API_KEY,
    base_url="https://openrouter.ai/api/v1"
)

documents = [
"""
SAS theorem states that if two sides and the included angle
of one triangle are equal to another triangle,
the triangles are congruent.
""",

"""
Binary Search Tree is a data structure
supporting efficient ordered lookup.
""",

"""
Newton's First Law states that an object remains
at rest or in motion unless acted on by force.
""",

"""
Python for loop is used to iterate through
collections such as lists and tuples.
"""
]

def generate_rationale(document):

    prompt = f"""
You are creating retrieval rationales.

Document:
{document}

Generate:

1. Why someone would search for this.
2. Related concepts.
3. Alternative phrasings.
4. Common user questions.

Keep under 100 words.
"""

    response = client.chat.completions.create(
        model="google/gemma-4-26b-a4b-it:free",
        messages=[
            {
                "role":"user",
                "content":prompt
            }
        ],
        temperature=0.3
    )

    return response.choices[0].message.content

def generate_rationale(document):

    prompt = f"""
You are creating retrieval rationales.

Document:
{document}

Generate:

1. Why someone would search for this.
2. Related concepts.
3. Alternative phrasings.
4. Common user questions.

Keep under 100 words.
"""

    response = client.chat.completions.create(
        model="nvidia/nemotron-3-super-120b-a12b:free",
        messages=[
            {
                "role":"user",
                "content":prompt
            }
        ],
        temperature=0.3
    )

    return response.choices[0].message.content

rationales = []

for doc in documents:

    r = generate_rationale(doc)

    rationales.append(r)

    print("="*60)
    print(r)

augmented_docs = []

for doc, rationale in zip(documents, rationales):

    combined = f"""
DOCUMENT:

{doc}

RATIONALE:

{rationale}
"""

    augmented_docs.append(combined)

embedder = SentenceTransformer(
    "BAAI/bge-small-en-v1.5"
)

vectors = embedder.encode(
    augmented_docs,
    normalize_embeddings=True
)

vectors = np.array(vectors).astype("float32")

vectors.shape

dimension = vectors.shape[1]

index = faiss.IndexFlatIP(
    dimension
)

index.add(vectors)

print(index.ntotal)

def search(query,k=3):

    qvec = embedder.encode(
        [query],
        normalize_embeddings=True
    )

    qvec = np.array(qvec).astype("float32")

    scores, ids = index.search(qvec,k)

    return scores[0], ids[0]

query = "how do I prove equal triangles"

scores, ids = search(query)

for score, idx in zip(scores, ids):

    print("\nSCORE:",score)
    print(augmented_docs[idx][:400])

def similarity(text1,text2):

    e = embedder.encode(
        [text1,text2],
        normalize_embeddings=True
    )

    return float(
        np.dot(e[0],e[1])
    )

query = "prove equal triangles"

original = documents[0]

augmented = augmented_docs[0]

reward = (
    similarity(query, augmented)
    -
    similarity(query, original)
)

print("Reward:", reward)

def generate_candidates(document,n=4):

    prompt = f"""
Document:

{document}

Generate {n} different retrieval rationales.

Format:

RATIONALE 1:
...

RATIONALE 2:
...
"""

    response = client.chat.completions.create(
        model="nvidia/nemotron-3-super-120b-a12b:free",
        messages=[
            {
                "role":"user",
                "content":prompt
            }
        ],
        temperature=0.9
    )

    return response.choices[0].message.content

doc = documents[0]

raw_candidates = generate_candidates(doc)

print(raw_candidates)

import re

parts = re.split(r"RATIONALE \d+:", raw_candidates)

candidates = [
    p.strip()
    for p in parts
    if p.strip()
]

print("Candidates:", len(candidates))

for i,c in enumerate(candidates):
    print("\n---")
    print(i)
    print(c[:200])

best_reward = -999

for rationale in candidates:

    augmented = doc + rationale

    reward = similarity(
        query,
        augmented
    )

    if reward > best_reward:
        best_reward = reward
        best_rationale = rationale

def get_best_rationale(doc, query):

    candidates = generate_candidates(doc)

    best_reward = -999
    best_rationale = None

    baseline = similarity(query, doc)

    for rationale in candidates:

        augmented = doc + "\n\n" + rationale

        reward = (
            similarity(query, augmented)
            - baseline
        )

        if reward > best_reward:
            best_reward = reward
            best_rationale = rationale

    return best_rationale, best_reward

def evaluate_rationale(doc, rationale, queries):

    augmented = doc + "\n\n" + rationale

    rewards = []

    for q in queries:

        baseline = similarity(q, doc)

        score = similarity(q, augmented)

        rewards.append(score - baseline)

    return np.mean(rewards)

doc = documents[0]

queries = [
    "triangle proof",
    "triangle congruence",
    "geometry theorem",
    "equal triangles"
]

candidates = generate_candidates(doc)

best_score = -999
best_rationale = None

for rationale in candidates:

    score = evaluate_rationale(
        doc,
        rationale,
        queries
    )

    print(score)

    if score > best_score:

        best_score = score
        best_rationale = rationale

print(best_rationale)

final_docs = []

for doc in documents:

    candidates = generate_candidates(doc)

    best_score = -999
    best_rationale = ""

    for rationale in candidates:

        score = similarity(
            rationale,
            doc
        )

        if score > best_score:

            best_score = score
            best_rationale = rationale

    final_docs.append(
        doc +
        "\n\nRETRIEVAL RATIONALE:\n" +
        best_rationale
    )

vectors = embedder.encode(
    final_docs,
    normalize_embeddings=True
)

vectors = np.array(vectors).astype("float32")

dimension = vectors.shape[1]

index = faiss.IndexFlatIP(
    dimension
)

index.add(vectors)

queries = [

    "how do I prove equal triangles",

    "fast searching sorted data",

    "repeat operation over every item",

    "object continues moving unless force acts"
]

for query in queries:

    print("\n")
    print("="*80)
    print("QUERY:", query)

    scores, ids = search(query)

    top_doc = final_docs[ids[0]]

    print(top_doc[:500])

